### ISSUE TITLE
Registering Slash command

### ISSUE THREAD

**Issue by 0xhua** [laracord/laracord#1]
I triend to create a slash command but it doesnt recognize after creating one. 

do i need to run some commands?

**Comment by 0xhua** [comment]
after creating the slash command in laracord

and running php laracord

slash command doesnt show in discord  


<img width="865" alt="Screenshot 2024-02-03 at 6 28 10 PM" src="https://github.com/laracord/laracord/assets/60700937/690e276c-8047-4f16-bcab-0639cb2e2521">

<img width="197" alt="Screenshot 2024-02-03 at 6 27 55 PM" src="https://github.com/laracord/laracord/assets/60700937/f23c7511-bf2f-4c39-8ef3-872abbcf460b">

**Comment by Log1x** [comment]
Does it show in the commands table after the bot boots?

**Comment by 0xhua** [comment]
it doesnt, do i need to clear some cache? if yes how? 

<img width="409" alt="Screenshot 2024-02-03 at 6 31 08 PM" src="https://github.com/laracord/laracord/assets/60700937/3ff264dc-354e-4b80-b0b6-98579f36ac2c">

<img width="394" alt="Screenshot 2024-02-03 at 6 31 17 PM" src="https://github.com/laracord/laracord/assets/60700937/c089a1ca-e353-4c6c-a970-99e2e870e555">

**Comment by Log1x** [comment]
Hmm, not entirely sure what is happening. Try making your slash command with capital casing for the class name:

```
php laracord make:slash-command TestCommand
```

If that doesn't work, what does the table look like in console when it boots?

Example: 

![Screenshot](https://i.imgur.com/EO9YBJ8.png)

If you still can't figure this out, add me on Discord – I will help: **Log1x**

**Comment by 0xhua** [comment]
added you :)

**Comment by Log1x** [comment]
Got this handled, even up being PSR-4 naming conventions. I will update the `make:` commands in the future to prevent this scenario.
