### ISSUE TITLE
Mysql?

### ISSUE THREAD

**Issue by Boendestodet** [laracord/laracord#3]
Is it possible to use mysql instead of sqlite?

**Comment by Log1x** [comment]
It should be possible but I need to make it easier.

I haven't tested it, but this should work:

- Copy [`config/database.php`](https://github.com/laracord/framework/blob/main/config/database.php) from Framework to your Laracord config folder.
- Copy the [MySQL configuration](https://github.com/laravel/laravel/blob/10.x/config/database.php#L46-L64) from Laravel's `database.php` config to `connections`

And then configure the following to your `.env`:

```env
DB_CONNECTION=mysql
DB_HOST=
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=
```

**Comment by Log1x** [comment]
I added support for this out of the box. You can go ahead and run `composer upgrade` and then delete that `database.php` config if you want.
