### ISSUE TITLE
A few questions about the project

### ISSUE THREAD

**Issue by mrfelipemartins** [laracord/laracord#4]
Hi @Log1x! I want to congratulate you for this awesome project! As a Laravel developer and active Discord user I have created a lot of bots a long the way using some manual implementations and other languages to fulfill that and now being able to build them within a Laravel familiar environment means a lot. Sorry to open an Issue for this, but the Discord invite link in the documentation is broken and there is no Discussion page in the repo. I have a few questions since I am still reading the docs and trying Laracord.

**HTTP Server**
If I want to create a page where users can subscribe to a premium plan of the bot, can I use the built-in HTTP Server or is it recommended that I use a separate Laravel project for that?

**Testing**
What about tests? Is there something discord-specific on the roadmap for testing? Should I stick to Laravel Zero's testing documentation for now? I couldn't find anything related to tests in the docs, hence the question.

**Discussions**
It would be really nice to have a discussions page in the repo for ideas/suggestions/bugs/questions! If there is no plan for that, please update the Discord server invite link so we can join!

Thanks and congratulations for the project!

**Comment by Log1x** [comment]
Sorry about the Discord invite being broken! I've fixed the redirect on the site, but here is the original: https://discord.gg/sAgPrRSUZg

I guess it kind of depends on what you're doing and the scale. The HTTP server could technically lock the thread and prevent the bot and other things from working, but I have not benched it or thoroughly tested it.

As far as tests, Laravel Zero's docs are a good starting point but I haven't personally approached it yet.

Hopefully we can get some discussion rolling in Discord. Sorry again about that!
