### ISSUE TITLE
[Doubt] Voice && Cron Possible

### ISSUE THREAD

**Issue by end3r-man** [laracord/laracord#9]
hello, first thank you so much creating laracord, and is it possible to use voice related thing in laracord and possible >>?? to setup cron job

**Comment by Log1x** [comment]
hey, no problem.

voice works with `$this->discord()->getVoiceClient($guildId)` but I don't think DiscordPHP has much documentation available for it so you'll have to rely on intellisense. I can maybe add an example to the Laracord docs soon.

for cron, it depends what you're trying to do, but its possible doing something with https://laracord.com/docs/services might make more sense so it runs on an interval inside of the loop and has access to the full state of the bot.

if you need more help, feel free to join the Discord server https://laracord.com/discord
